---
title: "COVID19 Impacts on smallholders literature"
output:
  pdf_document: default
  html_document: default
  word_document: default
bibliography: C:/Users/latzko/ownCloud/CRC 990/Landscape_Assessment/LandscapeAssessmentR/literature_review/covid_impacts_literature.bib
---


## @Chrisendo2020

#### Point of analysis \
* Association between oil palm cultivation and nutrition in smallholder farm households.
* also considering changes in income and gender roles
* First hypothesis: Oil palm cultivation is positively associated with household nutrition and dietary quality

#### Data \
Two rounds of C07 household farmer survey


#### Method

* Descriptives for comparing different groups of households
* run regression models
* random effects panel models
+ SUR estimator
+ logit estimator

#### Conclusion \

## @Josephson2021

#### Point of analysis \
Document the socioeconomic impacts of the pandemic among households, adults and children in low-income countries.

#### Data \
Longitudinal data from high-frequency phone surveys conducted in Ethiopia, Malawi, Nigeria and Uganda with support from the World Bank. These are based on the LSMS-ISA surveys that were conducted in each of these countries.
$n = 10,855$ households across four countries. 
Issues: selection bias and non-response bias

#### Method



#### Conclusion

* An estimated 77\% of the population live in households which has lost income since the start of the pandemic
* there is inability to access medicine and staple foods for an estimated 30% of households who would need these items

## @Kumar2021

#### Point of analysis \
Identify, describe and analyze the different factors affecting Indian farming systems, and more broadly the agricultural sector, following the COVID-19 lockdown which started in March, 2020.


#### Data 

* "Semi-empirical" research
* case study UP
* farmer survey:
  + 570 farmers spread across 57 districts in UP from March-May 2020
  + asked about farm operations and whether and how investment and profitability were affected

#### Method \
mixed methods

#### Conclusion \
Due to the pandemic, many laborers from the cities migrated back home to their villages. There they compete for local jobs.
Rural markets have ben wholly or partially closed to to lockdown. There was a government's relief package, though inadequate and not fulfilling the farmers' requirements. People below the povert line are supposed to not easily recover from the crisis. In 2020, wages in both agricultural and non-agricultural sector decreased, in fact stronger regarding the non-agricultural sector. Maybe this is due to the relief packages.

## @Adewopo2021

#### Point of analysis \

Assess the magnitude of price change over eleven weeks during and after the first COVID-related lockdown (2020), relative to the preceding year (2019).


#### Data \
Study area: northern Nigeria, where a pilot project to crowdsource food price data in Africa was led by the European Commission’s Joint Research Centre

* 23,961 spatially distributed datapoints, contributed by 236 active volunteers, on the price of four commodities (local rice, Thailand rice, white maize and yellow maize) 
* combined with spatial richness index grid derived from UN-FAO
  + data and information shortage between March and April 2020

#### Findings \

Results show that the retail price of maize (yellow and white) and rice (local and Thai rice) increased on average by respectively 26% and 44% during this COVID-related period, compared to prices reported in the same period in 2019. GPS-tracked data showed that mobility and market
access of active volunteers were reduced, travel-distance to market being 54% less in 2020 compared to 2019, and illustrates potential limitations on consumers who often seek lower pricing by accessing broader markets

#### Method \

In brief, the method consists of a series of steps implemented in algorithms (developed in R software) to assess spatial-temporal markets (clusters) of daily commodity prices, filter out spurious data points, and confine price values to reasonable attribute ranges.

#### Conclusion \

## @Bene2020

#### Point of analysis \

Explore and discuss the concept of local food system resilience in light of the disruptions brought to those systems by the 2020 COVID-19 pandemic.

#### Data \


#### Findings \

The review of existing (mainly grey or media-based) accounts on COVID-
19 suggests that, with the exception of those who lost members of their family to the virus, as per June 2020 the main impact of the pandemic derives mainly from the lockdown and mobility restrictions imposed by national/local governments, and the consequence that the subsequent loss of income and purchasing power has on people’s food security, in particular the poor.

#### Method \

#### Conclusion \

## @Mallory2021

#### Point of analysis \

* What the virus did to patterns of US and BRazilian exports of major commodities during the first surge of the virus during April and May, 2020.
  + detailed comparison of how US exports of soybeans, corn, beef and pork and poultry in the first 8 months of 2020 compared to the previous seven years. 
* And also speculate on what may happen during the beginning of North American winter in late 2020


#### Data \

* for grains: US export data from USDA AMS Federal Grain Inspection Service
* for meat:
  + NASS QuickStats and
  + USDA ERS Livestock and Meat Trade Data

#### Findings \

Grain, oil seed and poultry export shipments have been relatively unaffected but beef and pork export shipments experiences significant reductions with Brazil filling the shortfall in both cases.

#### Method \

Data comparison, descriptive statistics, speculation

#### Conclusion \

The crisis' necessary remedies do tremendous harm to the economy. Meat supply chains are especially vulnerable and disruptions to processing capacity harms farmers, processors, consumers and *our* trading partners

## @Olivia2020

#### Point of analysis \

* International dimensions of the Covid-19 crisis
  + focus on Covid in Indonesia
* Focus on economy
  + actual and projected impacts on growth
  + macroeconomic stability
  + international interactions
  + government's policy responses
* Social impacts and protection and poverty
* Potential long-term implications
 

#### Data \

* Mostly descriptive statistics and different national and international data sources, e.g.:
  + IMF
  + Covid-19 task force
  + WB data
  + BPS through CEIC

#### Findings \

* "at the time of writing, Covid-19 had not been tamed in Indonesia my any means."
* Poverty impacts remain uncertain but may be less severe than some other impacts
* Informal workers can be seriously hit by the crisis and its consequences such as social distancing measures and lockdowns


#### Method \


#### Conclusion \

*   The poverty impacts of the Covid-19 crisis (as of June, 2020) remain unvertain but may be less severe than some other impacts
*   Well-design stimulus measures will help once the pandemic has been brought under control

##### Potential long-term implications: 

* negative nutrition outcomes (stunting, wasting)
* Jordà, Singh and Taylor (2020) find that a shift to precautionary savings by households and individuals is typical during pandemics
* Increased risk aversion will further depress the equilibrium interest rate. Banks will have to hold the excess liquidity caused by a lack of viable projects due to expectations that repressed economic activity will continue. --> liquidity trap.
  + The massive increases in the supply of money are met with only limited use of it by households and businesses (Stiglitz and Rashid 2020) 


## @Obayelu2021

#### Point of analysis \

The study 

* assesses the trend of COVID-19 in Nigeria between the end of February 2020 till the beginning of January 2021;
* examines the immediate short-term and potential long-term effects of COVID-19 outbreak on the socioeconomics, agricultural systems, security of food and dietary intake in Nigeria;
* assesses the various actions taken against the COVID-19 in Nigeria to prevent deteriorating socioeconomic, food security and dietary intake conditions of people in Nigeria; and
* suggests the potential mitigation strategies to combat the effects of COVID-19 on agriculture, food security and nutrition in Nigeria.
* $N = 72$ respondents


#### Data \

* Mainly based on "personal observations, public opinion through mobile telephone survey of farm households
residing in Lagos and Ibadan in Lagos and Oyo States, Nigeria, respectively, but have their farms located outsides their places of residence.
* The study conducts a rapid assessment survey that comprised of a structured questionnaire package


#### Findings \

*   About 65% households interviewed was found to rationed food they eat
*   a COVID-19 impact survey conducted by the National Bureau of Statistics (NBS) shows that a 51% of households reduced their food consumption to cope with the shocks of the pandemic (NBS 2020)

#### Method \



#### Conclusion \

The shock of COVID-19 is not only a demand management problem but
a multidimensional crisis requiring monetary, fiscal, and health policy responses with global
collaboration and cooperation.


## @Goswami2021

#### Point of analysis \

The study explores the multiple pathways of present and future impact created by the pandemic and “Amphan” cyclonic storm on smallholder agricultural systems. Also, the study anticipates the behavior of the systems elements under different realistic scenarios of intervention. It also explored the severity and multi-faceted impacts of the pandemic on vulnerable smallholder agricultural production systems through in-depth interactions with key players at the micro-level.

#### Data \



#### Findings \



#### Methods \

* Qualitative exploration
  +   consultation with the key informants with whom the authors had been working for several years.
  +   conducted individual interviews with farmers by respecting the pandemic’s rule of social distancing, especially during the lockdown.
* Fuzzy cognitive mapping (FCM)
  +   FCM is a ‘mental modelling’ approach to create a map of cognition for individuals concerning a given problem space
  +   A mental model is an internally held representation of external reality by an individual (Jones et al., 2011) and
  may embody their reasoning about the structure and functioning of complex systems.
  +   multi-stakeholder workshops (for FCM), were not possible during the lockdown

#### Conclusion \


## @Suryahadi2020

#### Point of analysis \

Estimate the impact of Covid-19 on poverty in Indonesia

#### Data \

* Forecast is based on historical economic shocks in Indonesia.
  +   1997–98 Asian financial crisis.
  +   2005–06 large increases in the prices of fuel, especially kerosene
    -    rice price also increased
  
  
#### Findings \

see conclusion

#### Methods \

  * Translation of the impact of Covid-19 on economic growth into impact on average per capita household expenditure
  * $\Delta logPCE_t =\alpha +\beta \Delta gGDP_t +\epsilon$
    + $\Delta logPCE$ is change in the logarithm of average per capita household expenditure,
    + $\Delta gGDP$ is change in the rate of economic growth,
    + $\beta$ is the correlation parameter to be estimated
      - The model can be estimated using time series data on economic growth and average per capita household expenditure

#### Conclusion \

*   In contrast to the baseline projection of a 5% economic growth rate for 2020, various recent projections propose that Covid-19 will reduce Indonesia’s economic growth rate to between 4.2% and –3.5%.
* Best case scenario of Covid-19 impact (economic growth rate falls to 4.2%):
  + poverty rate increases from 9.2% in September 2019 to 9.7% by the end of 2020.
  + 1.3 mio people more in poverty
* worst-case scenario (economic growth rate falls to -3.5%):
  +   poverty rate increases to 16.6%
  +   19.7 million more people become poor
  

## @Goeb2020

#### Point of analysis \

To understand how Myanmar’s crop marketing system has been affected by the COVID-19 crisis, phone interviews were conducted with more than 100 agricultural commodity traders roughly every 30 days from late May until early August 2020. A round of qualitative interviews was also conducted with key informants on land-trading routes to China, Thailand, and India.

#### Data \

*  qualitative interviews with 100 agricultural commodity traders roughly every 30 days from late May until early August 2020 (4 months)

#### Findings \

Traders who reported that the pandemic is affecting their business in any way declined from 77 percent in late May to 43 percent in early August. Buying and marketing challenges were the most common disruptions reported in early August, followed by difficulties in collecting repayments on credit lent out to farmers. Increasing numbers of traders also reported difficulties in obtaining new loans or credit for their business.
  +   increased mobile phone use (ICTs) for marketing of products
* Higher shares of traders reported year-on-year decreases both in credit provision and in wholesale trading volumes in August compared to June.
* More traders report a decrease in competition than an increase since the crisis began.
* Crop buying and selling prices have been stable on average between April and August.
* Border gate closures at the China (Muse), Thailand (Myawaddy), and India (Tamu) borders have resulted in drastic reductions in overland exports of agricultural commodities since March 2020. Key informants said that there has been almost no crop trading to China and India, while exports to Thailand are down over half compared to a year ago.

##### Recommended actions for policy

* Coordinate domestic transport restrictions put in place in response to the recent second wave of COVID-19 to allow continued domestic trade of agricultural commodities.
* Facilitate safe exports of agricultural commodities. This should be done with formal agreements and government investments in monitoring and infrastructure. If borders remain closed into the monsoon harvest season later in 2020, farmers should expect to receive poor prices for their crops.
* Quickly expand the provision of loans for working capital to crop traders (CERP Action 2.1.1). This will enable traders to continue their buying activities through the coming harvest and prevent a possible decline in competition in the sector.
* Continue the waiver of the 2 percent withholding tax for crop traders (CERP Action 2.1.3).

#### Methods \

Qualitative interviews, descriptive statistics

#### Conclusion \

The qualitative interviews highlight the magnitude of the disruptions faced by agricultural commodity traders involved in cross-border trade due to COVID-19 restrictions. None of the respondents expects these restrictions to be lifted in time for the coming monsoon harvest. Decreased export demand for Myanmar’s agricultural commodities will put downward pressure on prices and have negative effects on Myanmar’s rural economies that already are hard hit by the COVID-19 crisis.


## @Yamamura2020

#### Point of analysis \

During the COVID 19 epidemic in Japan between March and April 2020 , Internet surveys were conducted to construct panel data to investigate change s at the individual level regarding preventive behaviors and mental condition s by surveying the same respondents at different times.

#### Data \

Internet surveys (not representative, seems like there was no sampling)

#### Findings \

* (1) the declaration led people to st ay home, while also
generating anger , fear, and anxiety 
* (2) The effect of the declaration on the promotion of
preventive behaviors was larger than the detrimental effect on mental condition s
* (3) Overall, the effect on women was larger than that on men.

##### Recommended actions for policy

> "An increase in anger from staying indoors is thought to cause domestic violence.
Considering this aspect is important when evaluating the outcomes of the state of emergency
declaration in Japan as well as lockdown s in Italy, France, Spain, the United Kingdom, and
the United States. Moreover, it is necessary to evaluate government policies through cost
benefit analysis from a long term viewpoint. Further research should investigate these aspects
to scrutinize whether Japanese government’s policy is more effective and efficient than
policies adopted by the USA, UK, French , Italy, and Spain"

#### Methods \

Difference-in-difference approach \
Treatment: declaration was held only for seven of these nine prefectures. The seven
prefectures where the declaration was held were defined as the treatment group. The two
remaining prefectures were defined as the control group. The number of individuals infected

#### Conclusion \


## @Aguero2020

#### Point of analysis \

Health shocks and their long-lasting impact on health behaviors:
Evidence from the 2009 H1N1 pandemic in Mexico

#### Data \

Several data sources, all but one, collected
by Mexico’s Ministry of Health (Secretaria de Salud) to create a state-year
balanced panel.

#### Findings \

> "We show that exogenous health shocks could facilitate the adoption of these behaviors (that are low-cost
but also difficult to adopt) and provide long-lasting effects on health outcomes. Specifically, we exploit the spatial and temporal variation of the 2009 H1N1 influenza pandemic in Mexico and show that areas with a higher incidence of H1N1 experienced larger reductions in diarrhea-related cases among young children. These reductions continue even three years after the shock ended. Health improvements and evidence of information seeking via Google searches were consistent with changes in hand washing behaviors. Several robustness checks validate our findings and mechanism."

##### Recommended actions for policy

> "Business-as-usual strategies, such as overall government health expenditures, vaccinations campaigns as well
changes in infrastructure (e.g., hospital beds) are unlikely to be behind the reasons for the decline in diarrhea cases. During major health emergencies, such as pandemics, individuals increase their demand for knowledge about ways to remain healthy (e.g. learning about better hygiene practice increases). If governments facilitate access to low cost information sources, such as search engines, (or hot lines, TV or radio spots), especially in areas where the disease is more prevalent, our results indicate that the public will use these resources to acquire information."

#### Methods \

> We exploit the temporal (the onset of the swine flu in 2009) and cross-sectional variation (by state) of the swine flu to examine its effect on diarrhea cases, that is, diseases that may be prevented with improved hygiene behavior that followed the onset of the H1N1 pandemic in Mexico. D.i.D. identification strategy using a balanced panel at the state and year-level: 

$y_{st}=\alpha + \beta H1N1_{st} + \tau_t + \theta_s + e_{st}$

"$y_{st}$ is the number of hospital discharges with a primary diagnosis of intestinal infections (henceforth referred to as diarrhea) for
state s in year t."

#### Conclusion \



## Reference list



